### ISSUE TITLE
double arrow in Safari for parallel

### ISSUE THREAD

**Issue by delightedbydhamma** [suttacentral/suttacentral#3222]
#### Description:
There are two arrows to pop down the parallels in Safari Version 17.4.1 (19618.1.15.11.14)

#### Steps to reproduce:

https://suttacentral.net/pli-tv-bi-vb-np?view=dense&lang=en

This could be related to [this bug](https://github.com/suttacentral/suttacentral/issues/3145) which I logged previously

#### Expected behaviour:

only one arrow :)

#### Screenshots:
<img width="794" alt="Screenshot 2024-07-18 at 2 57 19 PM" src="https://github.com/user-attachments/assets/8237f567-31b8-4264-a12f-6ccc0607612a">

**Comment by thesunshade** [comment]
Do you have the same issue on texts that have translations and the "Translations in other modern languages" line? Or is it just the parallels?

Just out of curiosity, are other websites this broken on Safari?

**Comment by delightedbydhamma** [comment]
No Bhante, other websites aren't this broken in Safari. Suttacentral is it's own kind of special.

Yes the double ups are _everywhere_

<img width="776" alt="Screenshot 2024-07-18 at 3 17 56 PM" src="https://github.com/user-attachments/assets/bbc3a55d-e53b-4a28-b2c4-ca79dfce59db">

**Comment by thesunshade** [comment]
> Suttacentral is it's own kind of special.

OK, I may have tracked down what is going on. These dropdowns are vanilla html `<details>` elements. By default they have the triangle you see. The way that the site is overriding that is with this css

```css
.section-details summary::before {
  display: inline-block;
  width: 24px;
  height: 24px;
  margin-right: 0px;
  margin-left: -8px;
  content: url("data:image/svg+xml;charset=UTF-8,<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24\" viewBox=\"0 -960 960 960\" width=\"24\"><path fill=\"rgb(168,164,156)\" d=\"M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z\"/></svg>");
  transition: 0.2s;
}
```

That `content:url(…` is the fancy arrow.

According to [this SO answer](https://stackoverflow.com/a/10813665) the `content` thing may have actually been done to accomodate Safari, however the SC code is missing the recommended `list-style: none`.

Are you on a desktop? Could you try to add the `list-style: none` in the inspector and see if that fixes it?
